MODULE I_PERSON
    IMPLICIT NONE

    TYPE, ABSTRACT :: PERSON
        CHARACTER (LEN = :), ALLOCATABLE :: NAME
        INTEGER :: AGE
        CONTAINS
            PROCEDURE(GET_PERSON_NAME_INTERFACE), DEFERRED :: GET_PERSON_NAME
            PROCEDURE(GET_PERSON_AGE_INTERFACE), DEFERRED :: GET_PERSON_AGE
    END TYPE PERSON

    INTERFACE
        SUBROUTINE GET_PERSON_NAME_INTERFACE(THIS, N)
            IMPORT
            CLASS(PERSON), INTENT(IN) :: THIS
            CHARACTER (LEN = :), INTENT(OUT), ALLOCATABLE :: N
        END SUBROUTINE GET_PERSON_NAME_INTERFACE
    END INTERFACE

    INTERFACE
        SUBROUTINE GET_PERSON_AGE_INTERFACE(THIS, A)
            IMPORT
            CLASS(PERSON), INTENT(IN) :: THIS
            INTEGER, INTENT(OUT) :: A
        END SUBROUTINE GET_PERSON_AGE_INTERFACE
    END INTERFACE
    
END MODULE I_PERSON