MODULE C_EXCEPTION
    IMPLICIT NONE

    INTERFACE RAISE
        MODULE PROCEDURE RAISE_EXCEPTION
    END INTERFACE
    
    CONTAINS
        SUBROUTINE RAISE_EXCEPTION(MESSAGE)
            CHARACTER(LEN = :), INTENT(IN), ALLOCATABLE :: MESSAGE
            PRINT *, MESSAGE
        END SUBROUTINE RAISE_EXCEPTION

ENDMODULE C_EXCEPTION