MODULE C_PERSON
    IMPLICIT NONE
    PRIVATE
    PUBLIC :: PERSON, GET_PERSON_NAME, GET_PERSON_AGE

    TYPE :: PERSON
        CHARACTER (LEN = :), ALLOCATABLE :: NAME
        INTEGER :: AGE
    END TYPE PERSON

CONTAINS 

    SUBROUTINE GET_PERSON_NAME(THIS, N)
        TYPE(PERSON), INTENT(IN) :: THIS
        CHARACTER (LEN = :), INTENT(OUT), ALLOCATABLE :: N
        N = THIS%NAME
    END SUBROUTINE GET_PERSON_NAME

    SUBROUTINE GET_PERSON_AGE(THIS, A)
        TYPE(PERSON), INTENT(IN) :: THIS
        INTEGER, INTENT(OUT) :: A
        A = THIS%AGE
    END SUBROUTINE GET_PERSON_AGE

END MODULE C_PERSON