PROGRAM MAIN
    USE C_PERSON
    IMPLICIT NONE
    TYPE(MAN) :: P
    CHARACTER (LEN = :), ALLOCATABLE :: P_NAME
    CHARACTER (LEN = :), ALLOCATABLE :: P_GENDER
    INTEGER :: P_AGE
    P = MAN("Someone", 5)
    CALL P%GET_PERSON_NAME(P_NAME)
    CALL P%GET_PERSON_AGE(P_AGE)
    CALL P%GET_PERSON_GENDER(P_GENDER)
    PRINT *, P_NAME , ' ', P_AGE, ' ', P_GENDER;

END PROGRAM MAIN