PROGRAM MAIN

    USE C_PERSON
    USE C_MATH
    USE C_EXCEPTION
    IMPLICIT NONE

    TYPE(MAN) :: P
    CHARACTER (LEN = :), ALLOCATABLE :: P_NAME
    CHARACTER (LEN = :), ALLOCATABLE :: P_GENDER
    INTEGER :: P_AGE

    REAL :: DIV_RESULT

    P = MAN("Someone", 5)
    CALL P%GET_PERSON_NAME(P_NAME)
    CALL P%GET_PERSON_AGE(P_AGE)
    CALL P%GET_PERSON_GENDER(P_GENDER)
    PRINT *, P_NAME, P_AGE, P_GENDER;

    

    DIV_RESULT = DIV(21.0, 0.0)

    PRINT *, ADD(3,6), ADD(3.2, 2.7), DIV_RESULT
END PROGRAM MAIN