PROGRAM MAIN
    USE C_PERSON
    IMPLICIT NONE
    TYPE(PERSON) :: P
    CHARACTER (LEN = :), ALLOCATABLE :: P_NAME
    INTEGER :: P_AGE
    P = PERSON("Someone", 5)
    CALL GET_PERSON_NAME(P, P_NAME)
    CALL GET_PERSON_AGE(P, P_AGE)
    PRINT *, P_NAME , ' ', P_AGE;

END PROGRAM MAIN